// SPDX-License-Identifier: Apache-2.0
// This code has been partially generated by an AI.

package plugin

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestNewProviderDefaultsName(t *testing.T) {
	t.Parallel()

	provider := NewProvider("")

	require.Equal(t, "publisher-oci", provider.Name())
	require.NoError(t, provider.HealthCheck(context.Background()))
}

func TestNewProviderUsesProvidedName(t *testing.T) {
	t.Parallel()

	provider := NewProvider("provider-example")

	require.Equal(t, "provider-example", provider.Name())
}
