// SPDX-License-Identifier: Apache-2.0
// This code has been partially generated by an AI.

package plugin

import (
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestResolveRefTemplate(t *testing.T) {
	t.Parallel()

	require.Equal(t, "ghcr.io/semrels/app:1.2.3", ResolveRef("ghcr.io/semrels/app:{version}", "1.2.3"))
}

func TestResolveRefAppendsTag(t *testing.T) {
	t.Parallel()

	require.Equal(t, "ghcr.io/semrels/app:1.2.3", ResolveRef("ghcr.io/semrels/app", "1.2.3"))
}

func TestParseArtifactsCSV(t *testing.T) {
	t.Parallel()

	artifacts, err := ParseArtifacts(func(key string) string {
		if key == "SEMREL_PLUGIN_ARTIFACTS" {
			return "dist/a.tar.gz,dist/b.tar.gz"
		}
		return ""
	})

	require.NoError(t, err)
	require.Equal(t, []string{"dist/a.tar.gz", "dist/b.tar.gz"}, artifacts)
}

func TestBuildOrasArgs(t *testing.T) {
	t.Parallel()

	args := BuildOrasArgs("ghcr.io/semrels/app:1.2.3", []string{"dist/app.tar.gz"})
	require.Equal(t, []string{"push", "ghcr.io/semrels/app:1.2.3", filepath.Clean("dist/app.tar.gz")}, args)
}
