// SPDX-License-Identifier: Apache-2.0
// This code has been partially generated by an AI.

package main

import (
	"context"
	"log"
	"os"

	grpcserver "github.com/SemRels/publisher-oci/internal/grpc"
	semrelplugin "github.com/SemRels/publisher-oci/internal/plugin"
)

func main() {
	provider := semrelplugin.NewProvider("publisher-oci")
	server := grpcserver.NewProviderServer(provider)

	if _, err := server.Health(context.Background()); err != nil {
		log.Printf("plugin health check failed: %v", err)
		os.Exit(1)
	}

	log.Printf("%s plugin template is ready", provider.Name())
}
